---
- name: "Installer HAProxy"
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: "Déployer la configuration HAProxy"
  ansible.builtin.template:
    src: haproxy.cfg.j2 # Ansible sait qu'il doit chercher dans le dossier templates/ du rôle !
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  notify: Redémarrer HAProxy

- name: "S'assurer que HAProxy est démarré"
  ansible.builtin.service:
    name: haproxy
    state: started
    enabled: yes
