plugin: community.proxmox.proxmox

url: "{{ lookup('env', 'PROXMOX_URL') }}"
user: "{{ lookup('env', 'PROXMOX_USER') }}"
token_id: "{{ lookup('env', 'PROXMOX_TOKEN_ID') }}"
token_secret: "{{ lookup('env', 'PROXMOX_TOKEN_SECRET') }}"
validate_certs: false

want_vms: true
want_proxmox_nodes_info: false

keyed_groups:
  - key: name
    separator: ""

compose:
  ansible_host: proxmox_agent_interfaces[0].ip_addresses[0]