---
- name: "Installer PostgreSQL et python3-psycopg2"
  ansible.builtin.apt:
    name:
      - postgresql-16
      - python3-psycopg2
    state: present
    update_cache: yes

- name: "Configurer la réplication et pg_hba.conf"

  ansible.builtin.debug:
    msg: "Ici se trouvent les tâches de réplication validées précédemment"
